### ISSUE TITLE
Query for a ITimeValue at an exact time state

### ISSUE THREAD

**Issue by martin-voigt** [4treesCH/strolch#5]
In public class TimeVariable<T extends IValue> the method

	public ITimeValue<T> getValueAt(final Long time) {
		ITimeValue<T> tmp = null;
		for (ITimeValue<T> value : this.container) {
			if (value.getTime() <= time) {
				tmp = value;
			} else {
				break;
			}
		}
		return tmp;
	}

return also states that are before a desired time. A method is required that also give a state at an exact time, thus uses:
**value.getTime().equals(time)**

**Comment by eitch** [comment]
I understand your need for this, but if you look at the following:

![statevariable](https://cloud.githubusercontent.com/assets/245382/24748835/4c589a2e-1ac1-11e7-8c03-1ce8fa97fb79.png)

then you will see that the idea of a state variable is that it always has a value at a given time. From time 0, it has the value 1, at time 1, value 1 and then there is a change at time 2 to value 3, thus time 3 also has this time and then again at time 4 we have a change to the value 0.

Thus the value is always defined at a given time. This is the idea of the state variables. If i would add a method which returns null, if the value does not exist, then you would also need to perform a check to see if the return value is null. Thus now you simply would need to perform a check on the time, if you want to be certain you have the value object at the specified time.

Nulls are always bad, thus it is actually not a good idea to introduce a new method which can return null. Further the existing methods should be modified to make sure they can't return null.
